version: "3.8"

services:
  db:
    restart: always
    container_name: db_whales
    hostname: db_whales
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DB_VOLUME_LOCAL_PATH}:/var/lib/mysql
    networks:
      - net_whales
    
  node:
    restart: always
    container_name: node_whales
    hostname: node_whales
    image: m6t6ng6/whales-uade-backend:0.9      # en prod
    #image: node:latest                         # en dev
    #command: npm start                         # en dev
    #working_dir: /home/node/app                # en dev
    environment:
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - APP_URL=${APP_URL}
      - APP_PORT=${APP_PORT}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - SECRET=${SECRET}
    ports:
      - "8000:${APP_PORT}"
    volumes:
      #- ./:/home/node/app                      # en dev
      - ./uploads/:/home/node/app/uploads
    depends_on:
      - db
    networks:
      - net_whales

networks:
  net_whales:
    external: true
    driver: "bridge"
    